name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: configmap-transformer-controller
      directory: docker/configmap-transformer-controller
    secrets: inherit
